# ============================================
# E-Commerce Sales & Customer Analysis
# Data Cleaning & Feature Engineering
# ============================================

In [1]:
# 1. Import libraries:
import pandas as pd
import numpy as np

In [2]:
#2. Load dataset:
df = pd.read_csv('sample_superstore.csv', encoding='latin1')
df.to_csv('fixed_file.csv', index=False, encoding='utf-8')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [4]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [3]:
# 3. Initial shape:
print("\nInitial Shape:", df.shape)

Initial Shape: (9994, 21)

# Data Cleaning

In [5]:
# 4. Remove duplicates:
duplicates = df.duplicated().sum()
print(f"/nDuplicate rows before removal: {duplicates}")
df = df.drop_duplicates()
print("Shape after removing duplicates:", df.shape)

/nDuplicate rows before removal: 0
Shape after removing duplicates: (9994, 21)

In [6]:
#5. Convert date columns:
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], errors='coerce')

In [7]:
# 6. Handle missing values:
print("\nMissing values before handling:")
print(df.isnull().sum())

Missing values before handling:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [9]:
# 7. For this dataset, usually minimal missing values:
df = df.dropna()
print("\nShape after dropping missing values:", df.shape)

Shape after dropping missing values: (9994, 21)

# Feature Engineering

In [15]:
# 8. Create Profit Margin:
df['Profit Margin'] = df['Profit'] / df['Sales']
print(df)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class
...      ...             ...        ...        ...             ...
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

           State  Postal Code Region       Product ID         Category  \
0       Kentucky        42420  South  FUR-BO-10001798        Furniture
1       Kentucky        42420  South  FUR-CH-10000454        Furniture
2     California        90036   West  OFF-LA-10000240  Office Supplies
3        Florida        33311  South  FUR-TA-10000577        Furniture
4        Florida        33311  South  OFF-ST-10000760  Office Supplies
...          ...          ...    ...              ...              ...
9989     Florida        33180  South  FUR-FU-10001889        Furniture
9990  California        92627   West  FUR-FU-10000747        Furniture
9991  California        92627   West  TEC-PH-10003645       Technology
9992  California        92627   West  OFF-PA-10004041  Office Supplies
9993  California        92683   West  OFF-AP-10002684  Office Supplies

     Sub-Category                                       Product Name  \
0       Bookcases                  Bush Somerset Collection Bookcase
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...
2          Labels  Self-Adhesive Address Labels for Typewriters b...
3          Tables      Bretford CR4500 Series Slim Rectangular Table
4         Storage                     Eldon Fold 'N Roll Cart System
...           ...                                                ...
9989  Furnishings                             Ultra Door Pull Handle
9990  Furnishings  Tenex B1-RE Series Chair Mats for Low Pile Car...
9991       Phones                              Aastra 57i VoIP phone
9992        Paper  It's Hot Message Books with Stickers, 2 3/4" x 5"
9993   Appliances  Acco 7-Outlet Masterpiece Power Center, Wihtou...

         Sales  Quantity  Discount    Profit  Profit Margin  \
0     261.9600         2      0.00   41.9136         0.1600
1     731.9400         3      0.00  219.5820         0.3000
2      14.6200         2      0.00    6.8714         0.4700
3     957.5775         5      0.45 -383.0310        -0.4000
4      22.3680         2      0.20    2.5164         0.1125
...        ...       ...       ...       ...            ...
9989   25.2480         3      0.20    4.1028         0.1625
9990   91.9600         2      0.00   15.6332         0.1700
9991  258.5760         2      0.20   19.3932         0.0750
9992   29.6000         4      0.00   13.3200         0.4500
9993  243.1600         2      0.00   72.9480         0.3000

      Shipping Time (Days)  Order Year  Order Month Order Month Name  \
0                        3        2016           11         November
1                        3        2016           11         November
2                        4        2016            6             June
3                        7        2015           10          October
4                        7        2015           10          October
...                    ...         ...          ...              ...
9989                     2        2014            1          January
9990                     5        2017            2         February
9991                     5        2017            2         February
9992                     5        2017            2         February
9993                     5        2017            5              May

     Sales Segment
0             High
1             High
2              Low
3             High
4              Low
...            ...
9989        Medium
9990        Medium
9991          High
9992        Medium
9993          High

[9994 rows x 27 columns]

In [16]:
# 9. Create Order Processing Time:
df['Shipping Time (Days)'] = (df['Ship Date'] - df['Order Date']).dt.days
print(df)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class
...      ...             ...        ...        ...             ...
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

           State  Postal Code Region       Product ID         Category  \
0       Kentucky        42420  South  FUR-BO-10001798        Furniture
1       Kentucky        42420  South  FUR-CH-10000454        Furniture
2     California        90036   West  OFF-LA-10000240  Office Supplies
3        Florida        33311  South  FUR-TA-10000577        Furniture
4        Florida        33311  South  OFF-ST-10000760  Office Supplies
...          ...          ...    ...              ...              ...
9989     Florida        33180  South  FUR-FU-10001889        Furniture
9990  California        92627   West  FUR-FU-10000747        Furniture
9991  California        92627   West  TEC-PH-10003645       Technology
9992  California        92627   West  OFF-PA-10004041  Office Supplies
9993  California        92683   West  OFF-AP-10002684  Office Supplies

     Sub-Category                                       Product Name  \
0       Bookcases                  Bush Somerset Collection Bookcase
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...
2          Labels  Self-Adhesive Address Labels for Typewriters b...
3          Tables      Bretford CR4500 Series Slim Rectangular Table
4         Storage                     Eldon Fold 'N Roll Cart System
...           ...                                                ...
9989  Furnishings                             Ultra Door Pull Handle
9990  Furnishings  Tenex B1-RE Series Chair Mats for Low Pile Car...
9991       Phones                              Aastra 57i VoIP phone
9992        Paper  It's Hot Message Books with Stickers, 2 3/4" x 5"
9993   Appliances  Acco 7-Outlet Masterpiece Power Center, Wihtou...

         Sales  Quantity  Discount    Profit  Profit Margin  \
0     261.9600         2      0.00   41.9136         0.1600
1     731.9400         3      0.00  219.5820         0.3000
2      14.6200         2      0.00    6.8714         0.4700
3     957.5775         5      0.45 -383.0310        -0.4000
4      22.3680         2      0.20    2.5164         0.1125
...        ...       ...       ...       ...            ...
9989   25.2480         3      0.20    4.1028         0.1625
9990   91.9600         2      0.00   15.6332         0.1700
9991  258.5760         2      0.20   19.3932         0.0750
9992   29.6000         4      0.00   13.3200         0.4500
9993  243.1600         2      0.00   72.9480         0.3000

      Shipping Time (Days)  Order Year  Order Month Order Month Name  \
0                        3        2016           11         November
1                        3        2016           11         November
2                        4        2016            6             June
3                        7        2015           10          October
4                        7        2015           10          October
...                    ...         ...          ...              ...
9989                     2        2014            1          January
9990                     5        2017            2         February
9991                     5        2017            2         February
9992                     5        2017            2         February
9993                     5        2017            5              May

     Sales Segment
0             High
1             High
2              Low
3             High
4              Low
...            ...
9989        Medium
9990        Medium
9991          High
9992        Medium
9993          High

[9994 rows x 27 columns]

In [17]:
# 10. Extract Date Features:
df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month
df['Order Month Name'] = df['Order Date'].dt.month_name()
print(df)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class
...      ...             ...        ...        ...             ...
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

           State  Postal Code Region       Product ID         Category  \
0       Kentucky        42420  South  FUR-BO-10001798        Furniture
1       Kentucky        42420  South  FUR-CH-10000454        Furniture
2     California        90036   West  OFF-LA-10000240  Office Supplies
3        Florida        33311  South  FUR-TA-10000577        Furniture
4        Florida        33311  South  OFF-ST-10000760  Office Supplies
...          ...          ...    ...              ...              ...
9989     Florida        33180  South  FUR-FU-10001889        Furniture
9990  California        92627   West  FUR-FU-10000747        Furniture
9991  California        92627   West  TEC-PH-10003645       Technology
9992  California        92627   West  OFF-PA-10004041  Office Supplies
9993  California        92683   West  OFF-AP-10002684  Office Supplies

     Sub-Category                                       Product Name  \
0       Bookcases                  Bush Somerset Collection Bookcase
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...
2          Labels  Self-Adhesive Address Labels for Typewriters b...
3          Tables      Bretford CR4500 Series Slim Rectangular Table
4         Storage                     Eldon Fold 'N Roll Cart System
...           ...                                                ...
9989  Furnishings                             Ultra Door Pull Handle
9990  Furnishings  Tenex B1-RE Series Chair Mats for Low Pile Car...
9991       Phones                              Aastra 57i VoIP phone
9992        Paper  It's Hot Message Books with Stickers, 2 3/4" x 5"
9993   Appliances  Acco 7-Outlet Masterpiece Power Center, Wihtou...

         Sales  Quantity  Discount    Profit  Profit Margin  \
0     261.9600         2      0.00   41.9136         0.1600
1     731.9400         3      0.00  219.5820         0.3000
2      14.6200         2      0.00    6.8714         0.4700
3     957.5775         5      0.45 -383.0310        -0.4000
4      22.3680         2      0.20    2.5164         0.1125
...        ...       ...       ...       ...            ...
9989   25.2480         3      0.20    4.1028         0.1625
9990   91.9600         2      0.00   15.6332         0.1700
9991  258.5760         2      0.20   19.3932         0.0750
9992   29.6000         4      0.00   13.3200         0.4500
9993  243.1600         2      0.00   72.9480         0.3000

      Shipping Time (Days)  Order Year  Order Month Order Month Name  \
0                        3        2016           11         November
1                        3        2016           11         November
2                        4        2016            6             June
3                        7        2015           10          October
4                        7        2015           10          October
...                    ...         ...          ...              ...
9989                     2        2014            1          January
9990                     5        2017            2         February
9991                     5        2017            2         February
9992                     5        2017            2         February
9993                     5        2017            5              May

     Sales Segment
0             High
1             High
2              Low
3             High
4              Low
...            ...
9989        Medium
9990        Medium
9991          High
9992        Medium
9993          High

[9994 rows x 27 columns]

In [18]:
#11. Create Sales Segments:
df['Sales Segment'] = pd.qcut(df['Sales'], q=3, labels=['Low', 'Medium', 'High'])
print(df)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class
...      ...             ...        ...        ...             ...
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

           State  Postal Code Region       Product ID         Category  \
0       Kentucky        42420  South  FUR-BO-10001798        Furniture
1       Kentucky        42420  South  FUR-CH-10000454        Furniture
2     California        90036   West  OFF-LA-10000240  Office Supplies
3        Florida        33311  South  FUR-TA-10000577        Furniture
4        Florida        33311  South  OFF-ST-10000760  Office Supplies
...          ...          ...    ...              ...              ...
9989     Florida        33180  South  FUR-FU-10001889        Furniture
9990  California        92627   West  FUR-FU-10000747        Furniture
9991  California        92627   West  TEC-PH-10003645       Technology
9992  California        92627   West  OFF-PA-10004041  Office Supplies
9993  California        92683   West  OFF-AP-10002684  Office Supplies

     Sub-Category                                       Product Name  \
0       Bookcases                  Bush Somerset Collection Bookcase
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...
2          Labels  Self-Adhesive Address Labels for Typewriters b...
3          Tables      Bretford CR4500 Series Slim Rectangular Table
4         Storage                     Eldon Fold 'N Roll Cart System
...           ...                                                ...
9989  Furnishings                             Ultra Door Pull Handle
9990  Furnishings  Tenex B1-RE Series Chair Mats for Low Pile Car...
9991       Phones                              Aastra 57i VoIP phone
9992        Paper  It's Hot Message Books with Stickers, 2 3/4" x 5"
9993   Appliances  Acco 7-Outlet Masterpiece Power Center, Wihtou...

         Sales  Quantity  Discount    Profit  Profit Margin  \
0     261.9600         2      0.00   41.9136         0.1600
1     731.9400         3      0.00  219.5820         0.3000
2      14.6200         2      0.00    6.8714         0.4700
3     957.5775         5      0.45 -383.0310        -0.4000
4      22.3680         2      0.20    2.5164         0.1125
...        ...       ...       ...       ...            ...
9989   25.2480         3      0.20    4.1028         0.1625
9990   91.9600         2      0.00   15.6332         0.1700
9991  258.5760         2      0.20   19.3932         0.0750
9992   29.6000         4      0.00   13.3200         0.4500
9993  243.1600         2      0.00   72.9480         0.3000

      Shipping Time (Days)  Order Year  Order Month Order Month Name  \
0                        3        2016           11         November
1                        3        2016           11         November
2                        4        2016            6             June
3                        7        2015           10          October
4                        7        2015           10          October
...                    ...         ...          ...              ...
9989                     2        2014            1          January
9990                     5        2017            2         February
9991                     5        2017            2         February
9992                     5        2017            2         February
9993                     5        2017            5              May

     Sales Segment
0             High
1             High
2              Low
3             High
4              Low
...            ...
9989        Medium
9990        Medium
9991          High
9992        Medium
9993          High

[9994 rows x 27 columns]

In [19]:
# 12. Discount Flag
df['High Discount'] = df['Discount'].apply(lambda x: 1 if x > 0.2 else 0)
print(df)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class
...      ...             ...        ...        ...             ...
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

           State  Postal Code Region       Product ID         Category  \
0       Kentucky        42420  South  FUR-BO-10001798        Furniture
1       Kentucky        42420  South  FUR-CH-10000454        Furniture
2     California        90036   West  OFF-LA-10000240  Office Supplies
3        Florida        33311  South  FUR-TA-10000577        Furniture
4        Florida        33311  South  OFF-ST-10000760  Office Supplies
...          ...          ...    ...              ...              ...
9989     Florida        33180  South  FUR-FU-10001889        Furniture
9990  California        92627   West  FUR-FU-10000747        Furniture
9991  California        92627   West  TEC-PH-10003645       Technology
9992  California        92627   West  OFF-PA-10004041  Office Supplies
9993  California        92683   West  OFF-AP-10002684  Office Supplies

     Sub-Category                                       Product Name  \
0       Bookcases                  Bush Somerset Collection Bookcase
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...
2          Labels  Self-Adhesive Address Labels for Typewriters b...
3          Tables      Bretford CR4500 Series Slim Rectangular Table
4         Storage                     Eldon Fold 'N Roll Cart System
...           ...                                                ...
9989  Furnishings                             Ultra Door Pull Handle
9990  Furnishings  Tenex B1-RE Series Chair Mats for Low Pile Car...
9991       Phones                              Aastra 57i VoIP phone
9992        Paper  It's Hot Message Books with Stickers, 2 3/4" x 5"
9993   Appliances  Acco 7-Outlet Masterpiece Power Center, Wihtou...

         Sales  Quantity  Discount    Profit  Profit Margin  \
0     261.9600         2      0.00   41.9136         0.1600
1     731.9400         3      0.00  219.5820         0.3000
2      14.6200         2      0.00    6.8714         0.4700
3     957.5775         5      0.45 -383.0310        -0.4000
4      22.3680         2      0.20    2.5164         0.1125
...        ...       ...       ...       ...            ...
9989   25.2480         3      0.20    4.1028         0.1625
9990   91.9600         2      0.00   15.6332         0.1700
9991  258.5760         2      0.20   19.3932         0.0750
9992   29.6000         4      0.00   13.3200         0.4500
9993  243.1600         2      0.00   72.9480         0.3000

      Shipping Time (Days)  Order Year  Order Month Order Month Name  \
0                        3        2016           11         November
1                        3        2016           11         November
2                        4        2016            6             June
3                        7        2015           10          October
4                        7        2015           10          October
...                    ...         ...          ...              ...
9989                     2        2014            1          January
9990                     5        2017            2         February
9991                     5        2017            2         February
9992                     5        2017            2         February
9993                     5        2017            5              May

     Sales Segment  High Discount
0             High              0
1             High              0
2              Low              0
3             High              1
4              Low              0
...            ...            ...
9989        Medium              0
9990        Medium              0
9991          High              0
9992        Medium              0
9993          High              0

[9994 rows x 28 columns]

# Quick validation

In [20]:
print("\n--- New Columns Created ---")
print(df.columns)

print("\n--- Sample Data ---")
display(df.head())

--- New Columns Created ---
Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Profit Margin', 'Shipping Time (Days)', 'Order Year', 'Order Month',
       'Order Month Name', 'Sales Segment', 'High Discount'],
      dtype='object')

--- Sample Data ---

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Margin,Shipping Time (Days),Order Year,Order Month,Order Month Name,Sales Segment,High Discount
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0.1600,3,2016,11,November,High,0
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0.3000,3,2016,11,November,High,0
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0.4700,4,2016,6,June,Low,0
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,-0.4000,7,2015,10,October,High,1
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,0.1125,7,2015,10,October,Low,0

# Save Clean Data

In [28]:
output_path = "http://localhost:8888/tree/Desktop/AI/cleaned_superstore.csv"
df.to_csv('cleaned_superstore.csv', index=False)
print(f"\nCleaned dataset saved to: {output_path}")

Cleaned dataset saved to: http://localhost:8888/tree/Desktop/AI/cleaned_superstore.csv

In [29]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Margin,Shipping Time (Days),Order Year,Order Month,Order Month Name,Sales Segment,High Discount
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0.1600,3,2016,11,November,High,0
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0.3000,3,2016,11,November,High,0
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0.4700,4,2016,6,June,Low,0
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,-0.4000,7,2015,10,October,High,1
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,0.1125,7,2015,10,October,Low,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,0.1625,2,2014,1,January,Medium,0
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,0.1700,5,2017,2,February,Medium,0
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,0.0750,5,2017,2,February,High,0
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,0.4500,5,2017,2,February,Medium,0
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,0.3000,5,2017,5,May,High,0